### ISSUE TITLE
trigger.xqm warning on a clean install

### ISSUE THREAD

**Issue by duncdrum** [HistoryAtState/frus#312]
during a clean install many errors are reported by the `trigger.xqm` module

```
2023-12-15 15:14:22 15 Dec 2023 14:14:22,034 [main] ERROR (DocumentTriggers.java [afterCreateDocument]:240) - Error during trigger prepare 
2023-12-15 15:14:22 org.exist.collections.triggers.TriggerException: Error during trigger prepare
2023-12-15 15:14:22     at org.exist.collections.triggers.XQueryTrigger.execute(XQueryTrigger.java:459) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.collections.triggers.XQueryTrigger.afterCreateDocument(XQueryTrigger.java:604) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.collections.triggers.DocumentTriggers.afterCreateDocument(DocumentTriggers.java:238) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.collections.MutableCollection.storeXMLInternal(MutableCollection.java:1389) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.collections.MutableCollection.storeXmlDocument(MutableCollection.java:1229) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.collections.MutableCollection.storeDocument(MutableCollection.java:1148) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.storage.NativeBroker.storeDocument(NativeBroker.java:2154) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.repo.Deployment.storeFiles(Deployment.java:805) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.repo.Deployment.scanDirectory(Deployment.java:742) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.repo.Deployment.lambda$30(Deployment.java:747) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
2023-12-15 15:14:22     at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
2023-12-15 15:14:22     at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
2023-12-15 15:14:22     at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
2023-12-15 15:14:22     at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
2023-12-15 15:14:22     at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
2023-12-15 15:14:22     at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
2023-12-15 15:14:22     at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
2023-12-15 15:14:22     at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
2023-12-15 15:14:22     at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
2023-12-15 15:14:22     at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
2023-12-15 15:14:22     at org.exist.repo.Deployment.scanDirectory(Deployment.java:747) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.repo.Deployment.scanDirectory(Deployment.java:716) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.repo.Deployment.deploy(Deployment.java:444) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.repo.Deployment.installAndDeploy(Deployment.java:281) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.repo.AutoDeploymentTrigger.execute(AutoDeploymentTrigger.java:125) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.storage.StartupTriggersManager.startPreMultiUserSystem(StartupTriggersManager.java:61) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.storage.BrokerPoolServicesManager.startPreMultiUserSystemServices(BrokerPoolServicesManager.java:264) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.storage.BrokerPool._initialize(BrokerPool.java:682) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.storage.BrokerPool.initialize(BrokerPool.java:451) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.storage.BrokerPools.configure(BrokerPools.java:177) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.storage.BrokerPools.configure(BrokerPools.java:112) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.jetty.JettyStart.run(JettyStart.java:217) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.jetty.JettyStart.main(JettyStart.java:103) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
2023-12-15 15:14:22     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
2023-12-15 15:14:22     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
2023-12-15 15:14:22     at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
2023-12-15 15:14:22     at org.exist.start.Main.invokeMain(Main.java:153) ~[exist-start-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.start.Main.runEx(Main.java:292) ~[exist-start-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.start.Main.run(Main.java:158) ~[exist-start-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.start.Main.main(Main.java:95) ~[exist-start-6.2.0.jar:6.2.0]
2023-12-15 15:14:22 Caused by: org.exist.xquery.XPathException: exerr:ERROR Could not locate collection: /db/apps/frus/frus-toc [at line 25, column 12, source: /db/apps/frus/modules/toc.xqm]
2023-12-15 15:14:22 In function:
2023-12-15 15:14:22     toc:generate-frus-toc(xs:string) [7:5:/db/apps/frus/modules/toc.xqm]
2023-12-15 15:14:22     trigger:after-create-document(item()*) [-1:-1:/db/apps/frus/modules/triggers.xqm]
2023-12-15 15:14:22     at org.exist.xquery.functions.xmldb.XMLDBAbstractCollectionManipulator.eval(XMLDBAbstractCollectionManipulator.java:157) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.xquery.BasicFunction.eval(BasicFunction.java:73) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:62) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.xquery.LetExpr.eval(LetExpr.java:110) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.xquery.LetExpr.eval(LetExpr.java:110) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.xquery.LetExpr.eval(LetExpr.java:110) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.xquery.LetExpr.eval(LetExpr.java:110) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.xquery.UserDefinedFunction.eval(UserDefinedFunction.java:161) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.xquery.FunctionCall.evalFunction(FunctionCall.java:289) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.xquery.FunctionCall.eval(FunctionCall.java:207) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.xquery.UserDefinedFunction.eval(UserDefinedFunction.java:161) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.xquery.FunctionCall.evalFunction(FunctionCall.java:289) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.xquery.FunctionCall.eval(FunctionCall.java:207) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.xquery.XQuery.execute(XQuery.java:442) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     at org.exist.collections.triggers.XQueryTrigger.execute(XQueryTrigger.java:445) ~[exist-core-6.2.0.jar:6.2.0]
2023-12-15 15:14:22     ... 41 more
```

**Comment by duncdrum** [comment]
this was fixed, there are no more errors in the log upon startup
